title: Ning Wang
position: MSc student in Systems, Control and Robotics
affiliation: KTH Royal Institute of Technology
email: ningwa@kth.se
keywords: 
google_scholar: 
github_link: https://github.com/lxpr
linkedin: https://www.linkedin.com/in/ningwa/?locale=en_US
avatar: 
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
